openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9

servers:
  - url: localhost:9999
    description: Metrics Sever is running here at /metrics
  - url: localhost:8080
    description: Server for the WebScraping data that will act as an API

paths:
  /life:
    get:
      description: Returns a "Hello World" message.
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: string
                example: "Hello World"
  /events:
    get:
      summary: Returns a list of events.
      description: Optional extended description in CommonMark or HTML.
      parameters:
        - in: query
          name: offset
          schema:
            type: integer
            default: 0
          required: true
          description: offset at which the DB should return the next X events to caller
        - in: query
          name: limit
          schema:
            type: integer
            default: 200
          required: true
          description: number of returned items
      responses:
        "200": # status code
          description: A JSON array of events
          content:
            application/json:
              schema:
                type: object
                properties:
                  total:
                    type: integer
                  has_more:
                    type: boolean
                  payload:
                    type: array
                    items:
                      $ref: "#/components/schemas/Event"
  /eventLocation:
    get:
      summary: "returns array of GeoPoints to caller. Also allows for filtering based on location based in"
      parameters:
        - in: query
          name: from
          schema: # pair of float64s but as strings "40.3/20.3" 
            type: string
            example: "40.65881334204/-73.874747519256"
          description: "Returns the X closest GeoPoints from the positon inputed"
        - in: query
          name: offset
          schema:
            type: integer
            default: 0
          required: true
          description: offset at which the DB should return the next X events to caller
        - in: query
          name: limit
          schema:
            type: integer
            default: 200
          required: true
          description: number of returned items
      responses:
        "200":
          description: A JSON array of GeoPoints
          content:
            application/json:
              schema:
                type: object
                properties:
                  total:
                    type: integer
                  has_more:
                    type: boolean
                  payload:
                    type: array
                    items:
                      $ref: "#/components/schemas/GeoPoint"
        "404":
          description: temp
        "405":
          description: temp
        "500":
          description: temp
              
components:
  schemas:
    Event:
      type: object
      properties:
        id:
          type: integer
        image_url:
          type: string
        host:
          type: string
        title:
          type: string
        date:
          type: string
        location:
          type: string
        description:
          type: string
        tags:
          type: string
        extra_info:
          type: string
        bio:
          type: string
        exact_address:
          type: boolean
        accepts_refund:
          type: boolean
    GeoPoint:
      type: object
      properties:
        id: 
          type: integer
        latitude: #float64
          type:
            number
        logitude: #float 64
          type:
            number
        address:
          type:
            string
        event_id:
          type:
            integer